# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{authorization-san}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra"]
  s.date = %q{2011-03-02}
  s.description = %q{A plugin for authorization in a ReSTful application.}
  s.email = %q{manfred@fngtps.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "lib/authorization.rb",
    "lib/authorization/allow_access.rb",
    "lib/authorization/block_access.rb",
    "lib/authorization/deprecated.rb",
    "rails/init.rb"
  ]
  s.homepage = %q{http://fingertips.github.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{A plugin for authorization in a ReSTful application.}
  s.test_files = [
    "examples/administrations_controller.rb",
    "examples/application.rb",
    "examples/application_with_multiple_auth_methods.rb",
    "examples/authenticated_controller.rb",
    "examples/page_controller_with_full_policy.rb",
    "examples/pages_controller.rb",
    "examples/public_controller.rb",
    "examples/users_controller.rb",
    "test/cases/behaviour_test.rb",
    "test/cases/deprecated_test.rb",
    "test/cases/internals_test.rb",
    "test/cases/structural_test.rb",
    "test/controllers/all.rb",
    "test/controllers/application_controller.rb",
    "test/controllers/authenticated_controller.rb",
    "test/controllers/broken_block_controller.rb",
    "test/controllers/complicated_controller.rb",
    "test/controllers/multiple_roles_controller.rb",
    "test/controllers/public_controller.rb",
    "test/controllers/users_controller.rb",
    "test/helpers/methods.rb",
    "test/models/resource.rb",
    "test/test_helper/rails2/test_helper.rb",
    "test/test_helper/rails3/test_helper.rb",
    "test/test_helper/shared.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

